# Generated by Django 4.1.7 on 2024-11-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_tankdata_last_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterUsageData",
            fields=[
                ("timestamp", models.DateTimeField(primary_key=True, serialize=False)),
                ("current_water_level", models.FloatField()),
                ("people_using_water", models.FloatField()),
                ("temperature", models.FloatField()),
                ("season", models.IntegerField()),
                ("time_of_day", models.IntegerField()),
                ("water_usage_last_hour", models.FloatField()),
                ("required_water", models.FloatField()),
            ],
            options={
                "db_table": "water_usage_data",
            },
        ),
    ]
