# Generated by Django 4.1.7 on 2024-11-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_waterusagedata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterusagedata",
            name="season",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="waterusagedata",
            name="time_of_day",
            field=models.TextField(),
        ),
    ]
